name: genchatapp
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  country_picker: ^2.0.27
#  http: ^1.2.2
  image_picker: ^1.1.2
  tenor_flutter: ^0.0.4
  pin_code_fields: ^8.0.1
  shared_preferences: ^2.3.3
  firebase_core: ^3.8.0
  firebase_messaging: ^15.1.5
  firebase_storage: ^12.3.6
  cloud_firestore: ^5.5.0
  cached_network_image: ^3.4.1
  intl: ^0.20.1
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  emoji_picker_flutter: ^3.1.0
  flutter_sound: ^9.17.5
  permission_handler: ^11.3.1
  path_provider: ^2.1.5
  swipe_to: ^1.0.6
  story_view: ^0.16.5
  timeago: ^3.2.2
  flutter_contacts: ^1.1.9+2
  sqflite: ^2.4.1
  connectivity_plus: ^6.1.0
  equatable: ^2.0.7
  dio: ^5.8.0+1
  socket_io_client: ^3.1.1
  rxdart: ^0.27.7
  scrollable_positioned_list: ^0.3.8
  encrypt: ^5.0.3
  flutter_dotenv: ^5.2.1
  material_symbols_icons: ^4.2815.0
  file_picker: ^9.0.0
  video_thumbnail: ^0.5.6
  open_file: ^3.5.10
#  image: ^4.5.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env
