const appName = "GenChat";
const appPackageName = "com.genmak.genchat";
const poweredBy = "Powered by";
const genmak = "Genmak";
const welcomeToGenchat = "WELCOME TO GENCHAT";
const tapAgreeAndContinue = "Tap 'Agree and continue' to accept the";
const genmakTermsOfServices = " Genmak Terms of\nService and Privacy Policy";
const agreeAndContinue = "AGREE AND CONTINUE";
const verifyPhoneNumber = "Verify your phone number";
const verifyNumberTextForShowing =
    "Genmak will send an SMS Message to verify your phone number. Enter your country code an phone number.";
const chooseACountry = "Choose a Country";
const requestOTP = "Request OTP";
const verificationCode = "Verification Code";
const createYurProfile = "Create your profile";
const next = "NEXT";
const newGroup = "New Group";
const settings = "Settings";
const clearText = "Clear chat";
const logout = "Logout";
const block = "Block";
const unBlock = "unBlock";

//Shared preferences Keys Names
const isNumVerify = "isNumberVerified";
const userUId = "userUId";
const userMob = "userMob";
const createUserProfile = "createUserProfile";
const usersDb = "usersDb";
const userDetail = "userDetail";
const contactsDb = "contactsDb";
const messageTable = "messageTable";
const deleteQueueTable = "deletion_queue";
const contactsSynced = "contactsSynced";
const chatConnectTable = "chatConnectTable";
const groupTable = "group_table";
const usersTable = "group_users_table";
const userGroupsTable = "user_groups_info";
const subscribedTopics = "subscribedTopics";
